"""add admin authentication

Revision ID: 29407bce07ff
Revises: 6b2ba0ef5e8a
Create Date: 2026-08-16 15:23:57.872185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29407bce07ff'
down_revision = '6b2ba0ef5e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))
        batch_op.drop_index(batch_op.f('ix_admins_active'))

    op.drop_table('admins')
    # ### end Alembic commands ###
