"""initial VoleiFlow schema

Revision ID: 6b2ba0ef5e8a
Revises:
Create Date: 2026-08-16 14:34:17.522238

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2ba0ef5e8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmation_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recurrence_group', sa.String(length=36), nullable=True),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_confirmation_deadline'), ['confirmation_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_recurrence_group'), ['recurrence_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_registration_opens_at'), ['registration_opens_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('offline_operations',
    sa.Column('operation_id', sa.String(length=80), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_offline_operations'))
    )
    with op.batch_alter_table('offline_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offline_operations_operation_type'), ['operation_type'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('required_per_team', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('name', name=op.f('uq_positions_name'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_active'), ['active'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('name', name=op.f('uq_shifts_name'))
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_active'), ['active'], unique=False)

    op.create_table('event_shifts',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_shifts_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_event_shifts_shift_id_shifts')),
    sa.PrimaryKeyConstraint('event_id', 'shift_id', name=op.f('pk_event_shifts'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('primary_position_id', sa.Integer(), nullable=False),
    sa.Column('secondary_position_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_level', sa.Integer(), nullable=False),
    sa.Column('reception', sa.Integer(), nullable=False),
    sa.Column('setting', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Integer(), nullable=False),
    sa.Column('serving', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_position_id'], ['positions.id'], name=op.f('fk_players_primary_position_id_positions')),
    sa.ForeignKeyConstraint(['secondary_position_id'], ['positions.id'], name=op.f('fk_players_secondary_position_id_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_primary_position_id'), ['primary_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_secondary_position_id'), ['secondary_position_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('balance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_teams_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_teams_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('event_id', 'shift_id', 'number', name='uq_team_event_shift_number')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_shift_id'), ['shift_id'], unique=False)

    op.create_table('blacklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('included_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_blacklist_entries_player_id_players')),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], name=op.f('fk_blacklist_entries_source_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklist_entries'))
    )
    with op.batch_alter_table('blacklist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_entries_included_at'), ['included_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_entries_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_entries_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_entries_removed_at'), ['removed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_entries_source_event_id'), ['source_event_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('primary_position_id', sa.Integer(), nullable=False),
    sa.Column('secondary_position_id', sa.Integer(), nullable=True),
    sa.Column('assigned_position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('absence_reason', sa.Text(), nullable=True),
    sa.Column('email_confirmation_token', sa.String(length=80), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_name', sa.String(length=160), nullable=False),
    sa.Column('snapshot_knowledge_level', sa.Integer(), nullable=False),
    sa.Column('snapshot_reception', sa.Integer(), nullable=False),
    sa.Column('snapshot_setting', sa.Integer(), nullable=False),
    sa.Column('snapshot_blocking', sa.Integer(), nullable=False),
    sa.Column('snapshot_serving', sa.Integer(), nullable=False),
    sa.Column('snapshot_attack', sa.Integer(), nullable=False),
    sa.Column('snapshot_defense', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_position_id'], ['positions.id'], name=op.f('fk_registrations_assigned_position_id_positions')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_registrations_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_registrations_player_id_players')),
    sa.ForeignKeyConstraint(['primary_position_id'], ['positions.id'], name=op.f('fk_registrations_primary_position_id_positions')),
    sa.ForeignKeyConstraint(['secondary_position_id'], ['positions.id'], name=op.f('fk_registrations_secondary_position_id_positions')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_registrations_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations')),
    sa.UniqueConstraint('event_id', 'player_id', 'shift_id', name='uq_registration_event_player_shift')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_assigned_position_id'), ['assigned_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_confirmed_at'), ['confirmed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_email_confirmation_token'), ['email_confirmation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_primary_position_id'), ['primary_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_secondary_position_id'), ['secondary_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_team_members_position_id_positions')),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_team_members_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('registration_id', name='uq_team_member_registration')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    now = datetime.now(timezone.utc)
    positions = sa.table(
        'positions',
        sa.column('name', sa.String), sa.column('required_per_team', sa.Integer),
        sa.column('active', sa.Boolean), sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(positions, [
        {'name': 'Ponteiro', 'required_per_team': 2, 'active': True, 'created_at': now, 'updated_at': now},
        {'name': 'Central', 'required_per_team': 2, 'active': True, 'created_at': now, 'updated_at': now},
        {'name': 'Líbero', 'required_per_team': 1, 'active': True, 'created_at': now, 'updated_at': now},
        {'name': 'Levantador', 'required_per_team': 1, 'active': True, 'created_at': now, 'updated_at': now},
        {'name': 'Oposto', 'required_per_team': 1, 'active': True, 'created_at': now, 'updated_at': now},
    ])
    settings = sa.table(
        'settings', sa.column('key', sa.String), sa.column('value', sa.JSON),
        sa.column('created_at', sa.DateTime(timezone=True)), sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(settings, [
        {'key': 'max_teams_per_event', 'value': 3, 'created_at': now, 'updated_at': now},
        {'key': 'confirmation_deadline_days', 'value': 1, 'created_at': now, 'updated_at': now},
        {'key': 'admin_whatsapp', 'value': '', 'created_at': now, 'updated_at': now},
        {'key': 'imbalance_threshold', 'value': 1.5, 'created_at': now, 'updated_at': now},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_registration_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_position_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_shift_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_secondary_position_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_primary_position_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_player_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_email_confirmation_token'))
        batch_op.drop_index(batch_op.f('ix_registrations_confirmed_at'))
        batch_op.drop_index(batch_op.f('ix_registrations_assigned_position_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('blacklist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_removed_at'))
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_player_id'))
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_origin'))
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_included_at'))

    op.drop_table('blacklist_entries')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_shift_id'))
        batch_op.drop_index(batch_op.f('ix_teams_event_id'))

    op.drop_table('teams')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_secondary_position_id'))
        batch_op.drop_index(batch_op.f('ix_players_primary_position_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_email'))
        batch_op.drop_index(batch_op.f('ix_players_active'))

    op.drop_table('players')
    op.drop_table('event_shifts')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_active'))

    op.drop_table('shifts')
    op.drop_table('settings')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_active'))

    op.drop_table('positions')
    with op.batch_alter_table('offline_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offline_operations_operation_type'))

    op.drop_table('offline_operations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_registration_opens_at'))
        batch_op.drop_index(batch_op.f('ix_events_recurrence_group'))
        batch_op.drop_index(batch_op.f('ix_events_game_date'))
        batch_op.drop_index(batch_op.f('ix_events_confirmation_deadline'))

    op.drop_table('events')
    # ### end Alembic commands ###
